language: elixir
elixir:
      - 1.0.0
      - 1.0.1
      - 1.0.2
      - 1.0.3
      - 1.0.4
      - 1.0.5
otp_release:
      - 17.3
      - 17.4
install: MIX_ENV=test mix deps.get --only test
sudo: false
