language: elixir
elixir:
      - 1.0.0
      - 1.0.1
      - 1.0.2
      - 1.0.3
      - 1.0.4
      - 1.0.5
otp_release:
      - 17.3
      - 17.4
      - 18.0
sudo: false
env:
      - ELIXIR_ERL_OPTIONS=""
      - ELIXIR_ERL_OPTIONS="+T 9"
