language: elixir
elixir:
      - 1.2.6
      - 1.3.0
      - 1.3.2
otp_release:
      - 19.0
      - 18.0
matrix:
    include:
        - elixir: 1.2.0
          otp_release: 18.0
        - elixir: 1.2.3
          otp_release: 18.0
sudo: false
